pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.7.0-debug
    tty: true
    command:
    - /busybox/sleep
    - infinity
    volumeMounts:
       - name: kaniko-secret
         mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
      - name: kaniko-secret
        secret:
            secretName: jfrog
            items:
            - key: .dockerconfigjson
              path: config.json    
'''
        }
    }
    parameters {
        string(name: 'DockerFile_Folder', description: 'docker folder for dockerfile of image')
        string(name: 'IMAGE_NAME', description: 'image name')
        string(name: 'IMAGE_TAG',  description: 'image tag')
    }    
    stages {
        stage('Build image') {
            environment {
                PATH = "/busybox:/kaniko:$PATH"
            }
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    git url: 'https://github.vodafone.com/VFGroup-MyVodafone-OnePlatform/DevOps-Resources.git', branch: 'pre-master', credentialsId: 'GHE-token'
                    sh '''#!/busybox/sh
                     /kaniko/executor --context ${DockerFile_Folder} --destination artifactory.vodafone.com/docker-vfgroup-oneplatform-local/${IMAGE_NAME}:${IMAGE_TAG} 
                    '''
                }
            }
        }
    }
}
